apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-temperatura-deployment
spec:
  selector:
    matchLabels:
      app: conversor-temperatura
  template:
    metadata:
      labels:
        app: conversor-temperatura
    spec:
      containers:
        - name: conversor-temperatura
          image: charleszt/conversor-temperatura:1.0
          ports:
            - protocol: TCP
              containerPort: 8080
          resources:
            limits:
               memory: "128Mi"
               cpu: "200Mi"                                         